StandaloneSimulatorMainCommandLineArgs:
    interface:
        type: "std::string"
        default: ""
        description: >-
            The interface to send and receive packets over (can be found through ifconfig)
    logging_dir:
        type: "std::string"
        default: ""
        description: >-
            The directory to output logs to. Logs will not be outputted if this argument
            is not used.
